
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Dockerbeat. They are
grouped in the following categories:

* <<exported-fields-env>>
* <<exported-fields-container>>
* <<exported-fields-net>>
* <<exported-fields-memory>>
* <<exported-fields-blkio>>
* <<exported-fields-cpu>>
* <<exported-fields-log>>

[[exported-fields-env]]
=== Common Fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Can be one of *container*, *cpu*, *net*, *memory*, *blkio* to specify metric type.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== containerID

type: string

required: True

Docker container ID related to the current metric event.


==== containerName

type: string

required: True

Name of the Docker container related to the current metric event.


==== dockerSocket

type: string

required: True

URI to the monitored docker daemon.


=== containerLabels Fields

Array of label metadata of the Docker container.



==== containerLabels.key

type: string

Key of the container label.


==== containerLabels.value

type: string

Value of the container label.


==== beat.name

Name of the Beat sending the events. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[[exported-fields-container]]
=== Container information Fields

Contains container informations. Details that you can get by running a *docker ps* command.



[[exported-fields-container]]
=== Container information Fields


==== container.command

type: string

Command used to run the Docker container.


==== container.created

type: date

example: 2015-01-24 14:06:05

format: YYYY-MM-DDTHH:MM:SSZ

Date of the Docker container creation.


==== container.id

type: string

ID of the Docker container.


==== container.image

type: string

Name of the Docker image from which contained has been launched.


==== container.names

type: string

Human readable names of the container.


=== ports Fields

List of published ports.



==== container.ports.ip

type: string

Binding IP.


==== container.ports.privatePort

type: integer

Private port (container side) of the binding.


==== container.ports.publicPort

type: integer

Public port (host side) of the binding.


==== container.ports.type

type: string

Type of binding. Can be either *tcp* or *udp*.


==== container.sizeRootFs

type: float

TODO


==== container.sizeRw

type: string

TODO


==== container.status

type: string

Status of the container.


[[exported-fields-net]]
=== Network usage Fields

Gather container metrics about network (rx/tx)



[[exported-fields-net]]
=== Network usage Fields


==== net.name

type: string

Name of the network interface.


==== net.rxBytes_ps

type: float

Average number of bytes received per second since the last event.


==== net.rxDropped_ps

type: float

Average received dropped packets per second since the last event.


==== net.rxErrors_ps

type: float

Average number of errors received per second since the last event.


==== net.rxPackets_ps

type: float

Average number of packets received per second since the last event.


==== net.txBytes_ps

type: float

Average number of bytes transmitted per second since the last event.


==== net.txDropped_ps

type: float

Average transmitted dropped packets per second since the last event.


==== net.txErrors_ps

type: float

Average number of errors transmitted per second since the last event.


==== net.txPackets_ps

type: float

Average number of packets transmitted per second since the last event.


[[exported-fields-memory]]
=== Memory consumption Fields

Contains metrics about container memory usage.



[[exported-fields-memory]]
=== Memory consumption Fields


==== memory.failcnt

type: float

TODO


==== memory.limit

type: float

Limit of memory (max memory available) in Bytes.


==== memory.maxUsage

type: float

Maximum memory used by the container in Bytes.


==== memory.totalRss

type: float

"Current RSS (applications' Resident Set Size) memory consumption in Bytes."


==== memory.totalRss_p

type: float

"Current RSS (applications' Resident Set Size) memory consumption in percents between 0.0 and 1.0."


==== memory.usage

type: float

Current memory consumption in Bytes.


==== memory.usage_p

type: float

Amount of memory used by the container in percents between 0.0 and 1.0.


[[exported-fields-blkio]]
=== IO disk usage Fields

Gather disk usage of the current container.



[[exported-fields-blkio]]
=== IO disk usage Fields


==== blkio.read_ps

type: int

It represents average amount of bytes read per second by the container on disk(s) during the period.


==== blkio.write_ps

type: int

It represents average amount of bytes written per second by the container on disk(s) during the period.


==== blkio.total_ps

type: int

It represents average amount of bytes read and written per second by the container on disk(s) during the period.


[[exported-fields-cpu]]
=== CPU consumption Fields

Gather cpu consumption of the current container.



[[exported-fields-cpu]]
=== CPU consumption Fields


==== cpu.totalUsage

type: float

Total cpu consumption in percent. This value can be greater than 100%, depending on the number of available CPUs.


==== cpu.usageInKernelmode

type: float

Same as *totalUsage*, but only the Kernel mode consumptions.


==== cpu.usageInUsermode

type: float

Same as *totalUsage*, but only the User mode consumptions.


=== percpuUsage Fields

Detailled cpu consumption per cpu (in percent).



==== cpu.percpuUsage.cpu0

type: float

==== cpu.percpuUsage.cpu1

type: float

==== cpu.percpuUsage.cpu2

type: float

==== cpu.percpuUsage.cpu3

type: float

==== cpu.percpuUsage.cpu4

type: float

==== cpu.percpuUsage.cpu5

type: float

==== cpu.percpuUsage.cpu6

type: float

==== cpu.percpuUsage.cpu7

type: float

==== cpu.percpuUsage.cpu8

type: float

==== cpu.percpuUsage.cpu9

type: float

==== cpu.percpuUsage.cpu10

type: float

==== cpu.percpuUsage.cpu11

type: float

==== cpu.percpuUsage.cpu12

type: float

==== cpu.percpuUsage.cpu13

type: float

==== cpu.percpuUsage.cpu14

type: float

==== cpu.percpuUsage.cpu15

type: float

==== cpu.percpuUsage.cpu16

type: float

==== cpu.percpuUsage.cpu17

type: float

==== cpu.percpuUsage.cpu18

type: float

==== cpu.percpuUsage.cpu19

type: float

==== cpu.percpuUsage.cpu20

type: float

==== cpu.percpuUsage.cpu21

type: float

==== cpu.percpuUsage.cpu22

type: float

==== cpu.percpuUsage.cpu23

type: float

[[exported-fields-log]]
=== Logs about dockerbeat agent status Fields

Special event sent by dockerbeat to log some events.



[[exported-fields-log]]
=== Logs about dockerbeat agent status Fields


==== log.level

type: string

Log level (debug, info, warning, error, fatal).


==== log.message

type: string

Log message.


