
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Dockerbeat. They are
grouped in the following categories:

* <<exported-fields-env>>
* <<exported-fields-dockerbeat>>

[[exported-fields-env]]
=== Common Fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp of when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

PLEASE UPDATE DOCUMENTATION


==== count

type: int

required: True

The number of transactions that this event represents. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== beat.name

Name of the Beat sending the events. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


